export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_COUNT = "ADJUST_ITEM_COUNT";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUB_QUANTITY = "SUB_QUANTITY";
